### ISSUE TITLE
Error generated on PlayerJoinEvent

### ISSUE THREAD

**Issue by APG77** [wacossusca34/Consoles#14]
[13:21:11] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Consoles v1.8a-beta
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Bukkit-53fac9f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:282) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:142) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:115) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:53) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:222) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(SourceFile:168) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:744) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [craftbukkit.jar:git-Bukkit-53fac9f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.server.v1_8_R3.NetworkManager.l from class ca.jarcode.consoles.util.NetworkManagerWrapper
        at ca.jarcode.consoles.util.NetworkManagerWrapper.init(NetworkManagerWrapper.java:121) ~[?:?]
        at ca.jarcode.consoles.util.NetworkManagerWrapper.wrap(NetworkManagerWrapper.java:82) ~[?:?]
        at ca.jarcode.consoles.util.PacketUtils.wrapNetworkManager(PacketUtils.java:139) ~[?:?]
        at ca.jarcode.consoles.util.PacketUtils.registerOutListener(PacketUtils.java:114) ~[?:?]
        at ca.jarcode.consoles.internal.ConsoleHandler.onPlayerJoin(ConsoleHandler.java:374) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit.jar:git-Bukkit-53fac9f]
        ... 14 more
[13:21:11] [Server thread/INFO]: kianagarcia[/98.255.214.108:49838] logged in with entity id 442000 at ([world]185.30000001192093, 141.0, -574.8502605055999)

**Comment by wacossusca34** [comment]
Thanks. Sorry for the delay, I will get around to looking at this.

Some information about your server would be useful, this error is admittedly confusing because it is throwing an error during reflection on a field that is explicitly used in the code.

**Comment by wacossusca34** [comment]
stack trace now points to invalid line numbers, could not reproduce errors. I'm assuming this was a non-standard server (paperspigot?) and something was patched causing the networkmanager wrapper to get confused.

**Comment by APG77** [comment]
The server is 1.8.8 craftbukkit compiled from the Spigot build tools.

**Comment by wacossusca34** [comment]
Thanks, for now I am only supporting spigot servers. This looks like an issue with spigot patches to craftbukkit resulting in a different networkmanager class.
