### ISSUE TITLE
Unsupported major.m inor version 52.0

### ISSUE THREAD

**Issue by zedwick** [wacossusca34/Consoles#2]
[02:15:02 ERROR]: Could not load 'plugins/consoles.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: jarcode/consoles/ConsolesLoader : Unsupported major.m
inor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[lL.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[lL.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [lL.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:291) [lL.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:199) [lL.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [lL.jar:git-Spigot-870264a-0a645a2]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.UnsupportedClassVersionError: jarcode/consoles/ConsolesLoader : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_79]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_79]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_79]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_79]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_79]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_79]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_79]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_79]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[lL.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[lL.jar:git-Spigot-870264a-0a645a2]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_79]
        at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[lL.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[lL.jar:git-Spigot-870264a-0a645a2]
        ... 6 more

**Comment by zedwick** [comment]
I can now see the note about only working in Java 8 at the top, I had only checked the FAQ.

**Comment by wacossusca34** [comment]
Thanks for re-reading and finding the issue yourself :)

**Comment by zedwick** [comment]
Yeah, I've seen other plugin devs who just happened to compile with the latest java because that's what they were using, not because they needed anything new from it. Just seeing that you were aware of the requirement suggests you are compiling against java 8 for a good reason, so I'm happy :)

**Comment by wacossusca34** [comment]
If there was some easy way I could provide a separate jar with Java 7 support, I would, but `javac` does not provide any backwards compatibility for lambdas (which is surprising because they could easily be translated into anonymous classes with static analysis).

Default methods would have to be compiled differently, however, but not in a way that would require any code changes (placing the default method in the implementing classes as Java 7 does not allow interface methods with bodies).

Makes me want to make a simple wrapper that allows Java 8 code to be compiled as Java 7 bytecode - some instrumentation on the resulting class files after the removal of default methods would allow for that backwards support (if I can find a way to forcefully compile invalid `invokedynamic` opcodes...)

We'll see :)
