### ISSUE TITLE
Invalid Plugin Exception

### ISSUE THREAD

**Issue by jackmawer** [wacossusca34/Consoles#31]
[09:21:34] [Server thread/ERROR]: Could not load 'plugins/consoles-core-1.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: ca/jarcode/consoles/v1_8_R3/NMSModule
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: ca/jarcode/consoles/v1_8_R3/NMSModule
        at ca.jarcode.consoles.NMSHandler.<clinit>(NMSHandler.java:17) ~[?:?]
        at ca.jarcode.consoles.Consoles.<init>(Consoles.java:37) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_66]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_66]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_66]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_66]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        ... 6 more
Caused by: java.lang.NoClassDefFoundError: ca/jarcode/consoles/v1_8_R3/NMSModule
        at ca.jarcode.consoles.NMSHandler.<clinit>(NMSHandler.java:17) ~[?:?]
        at ca.jarcode.consoles.Consoles.<init>(Consoles.java:37) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_66]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_66]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_66]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_66]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: ca.jarcode.consoles.v1_8_R3.NMSModule
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66]
        at ca.jarcode.consoles.NMSHandler.<clinit>(NMSHandler.java:17) ~[?:?]
        at ca.jarcode.consoles.Consoles.<init>(Consoles.java:37) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_66]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_66]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_66]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_66]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        ... 6 more
[09:21:34] [Server thread/ERROR]: Could not load 'plugins/consoles-computers-1.2.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: ConsolesCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

What am I missing?

**Comment by jackmawer** [comment]
Using Java 8, Spigot 1.8.7.

**Comment by jackmawer** [comment]
Redownloading 'fixed' this.

**Comment by wacossusca34** [comment]
I think some builds of the plugin don't have all the dependencies packed? This is an odd one. Again, I caught the issue in the `pom.xml` for `consoles-computers` a while back and will be fixed in 1.3.

**Comment by jackmawer** [comment]
Yep, it seems I downloaded the build without dependencies, and I can confirm downloading the version with dependencies worked fine. Clicking the download link brought up a version without dependencies, right clicking, copying the link and wgetting the file seemed to include the dependencies.

**Comment by wacossusca34** [comment]
that makes zero sense, so I'm just going to blame it on the user
