### ISSUE TITLE
Missing libcomputerimpl.so

### ISSUE THREAD

**Issue by jackmawer** [wacossusca34/Consoles#32]
[14:03:13] [Server thread/WARN]: java.nio.file.NoSuchFileException: /root/rchurchil/plugins/ConsolesComputers/libcomputerimpl.so
[14:03:13] [Server thread/WARN]:        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[14:03:13] [Server thread/WARN]:        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[14:03:13] [Server thread/WARN]:        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[14:03:13] [Server thread/WARN]:        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
[14:03:13] [Server thread/WARN]:        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
[14:03:13] [Server thread/WARN]:        at java.nio.file.Files.newOutputStream(Files.java:216)
[14:03:13] [Server thread/WARN]:        at java.nio.file.Files.copy(Files.java:3016)
[14:03:13] [Server thread/WARN]:        at ca.jarcode.consoles.computer.NativeLoader.extractLib(NativeLoader.java:97)
[14:03:13] [Server thread/WARN]:        at ca.jarcode.consoles.computer.NativeLoader.loadAsJNILibrary(NativeLoader.java:66)
[14:03:13] [Server thread/WARN]:        at ca.jarcode.consoles.Computers.onEnable(Computers.java:49)
[14:03:13] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[14:03:13] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[14:03:13] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:03:13] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[14:03:13] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[14:03:13] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[14:03:13] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[14:03:13] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)
[14:03:13] [Server thread/ERROR]: Error occurred while enabling ConsolesComputers v1.2 (Is it up to date?)
java.lang.RuntimeException: Unsupported platform
        at ca.jarcode.consoles.computer.NativeLoader.extractLib(NativeLoader.java:104) ~[?:?]
        at ca.jarcode.consoles.computer.NativeLoader.loadAsJNILibrary(NativeLoader.java:66) ~[?:?]
        at ca.jarcode.consoles.Computers.onEnable(Computers.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

Help, please?

**Comment by soccermitchy** [comment]
I got that error too, what I did to fix it was cd to the plugins folder
then mkdir ConsolesComputers since apperantly Jarcode forgot to put that in
the code...

**Comment by jackmawer** [comment]
Thanks, that worked. leaving this open for a proper fix however.

**Comment by wacossusca34** [comment]
Latest version of the plugin is bugged for a number of reasons, I would update if I wasn't in the middle of a long debugging process. Keep an eye out for version 1.3!

**Comment by wacossusca34** [comment]
this _has_ been fixed a number of days back, though, so I'm just going to close this for now since the next version will have better library loading and not the stupid folder bug.
