### ISSUE TITLE
Dosen't work at all on a _LINUX SERVER_

### ISSUE THREAD

**Issue by dittoslash** [wacossusca34/Consoles#41]
Server specs:
Craftbukkit, built with buildtools.jar on MC version... 1.8.8 (run with -Xmx4G and -Xms4G, 8G total ram)
Debian Jessie (9 or something)
(Server dir: /home/henry/messland)

clip from startup log:
[18:18:00 INFO]: [ConsolesCore] Enabling ConsolesCore v1.2
[18:18:00 INFO]: [ConsolesCore] Loaded command: CommandConsole
[18:18:00 INFO]: [ConsolesCore] Loaded command: CommandImage
[18:18:00 INFO]: [ConsolesComputers] Enabling ConsolesComputers v1.2
[18:18:00 WARN]: java.nio.file.NoSuchFileException: /home/henry/messland/plugins/ConsolesComputers/libcomputerimpl.so
[18:18:00 WARN]:        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[18:18:00 WARN]:        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[18:18:00 WARN]:        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[18:18:00 WARN]:        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
[18:18:00 WARN]:        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
[18:18:00 WARN]:        at java.nio.file.Files.newOutputStream(Files.java:216)
[18:18:00 WARN]:        at java.nio.file.Files.copy(Files.java:3016)
[18:18:00 WARN]:        at ca.jarcode.consoles.computer.NativeLoader.extractLib(NativeLoader.java:97)
[18:18:00 WARN]:        at ca.jarcode.consoles.computer.NativeLoader.loadAsJNILibrary(NativeLoader.java:66)
[18:18:00 WARN]:        at ca.jarcode.consoles.Computers.onEnable(Computers.java:49)
[18:18:00 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[18:18:00 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[18:18:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[18:18:00 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342)
[18:18:00 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314)
[18:18:00 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:252)
[18:18:00 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:69)
[18:18:00 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14)
[18:18:00 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179)
[18:18:00 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:503)
[18:18:00 WARN]:        at java.lang.Thread.run(Thread.java:745)
[18:18:00 ERROR]: Error occurred while enabling ConsolesComputers v1.2 (Is it up to date?)
java.lang.RuntimeException: Unsupported platform
        at ca.jarcode.consoles.computer.NativeLoader.extractLib(NativeLoader.java:104) ~[?:?]
        at ca.jarcode.consoles.computer.NativeLoader.loadAsJNILibrary(NativeLoader.java:66) ~[?:?]
        at ca.jarcode.consoles.Computers.onEnable(Computers.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Bukkit-9cd1111]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit.jar:git-Bukkit-9cd1111]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-9cd1111]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342) [craftbukkit.jar:git-Bukkit-9cd1111]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314) [craftbukkit.jar:git-Bukkit-9cd1111]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:252) [craftbukkit.jar:git-Bukkit-9cd1111]
        at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:69) [craftbukkit.jar:git-Bukkit-9cd1111]
        at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-9cd1111]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179) [craftbukkit.jar:git-Bukkit-9cd1111]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:503) [craftbukkit.jar:git-Bukkit-9cd1111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by soccermitchy** [comment]
Make sure the ConsolesComputers dir exists in the plugins folder, I had
that issue a while back

**Comment by wacossusca34** [comment]
Issue with the older version of the plugin, the current branch has this resolved. Just an issue with creating the plugin directory at early load stages (so you'll have to do it manually).

**Comment by dittoslash** [comment]
Woohoo, thanks!
