### ISSUE TITLE
Console showing up with world as "null", gives NPE when attempted to remove

### ISSUE THREAD

**Issue by tmad40blue** [wacossusca34/Consoles#47]
I've got one console that shows up when I do ````/console list```` that has its world listed as "null". When I attempt to remove it using ````/console remove 1```` it gives a NPE in my server console. All other consoles on the server work fine.

Screenshot of ````/console list```` output:

![Screenshot of command output](http://i.imgur.com/jMd9Aph.png)
Error:

````
[14:21:10 WARN]: java.lang.NullPointerException
[14:21:10 WARN]:        at ca.jarcode.consoles.internal.ConsolePixelBuffer.remove(ConsolePixelBuffer.java:181)
[14:21:10 WARN]:        at ca.jarcode.consoles.internal.ConsoleRenderer.remove(ConsoleRenderer.java:326)
[14:21:10 WARN]:        at ca.jarcode.consoles.internal.ManagedConsole.remove(ManagedConsole.java:60)
[14:21:10 WARN]:        at ca.jarcode.consoles.internal.ManagedConsole.remove(ManagedConsole.java:57)
[14:21:10 WARN]:        at ca.jarcode.consoles.command.CommandConsole.onCommand(CommandConsole.java:50)
[14:21:10 WARN]:        at ca.jarcode.consoles.command.CommandHandler.handle(CommandHandler.java:91)
[14:21:10 WARN]:        at ca.jarcode.consoles.command.CommandHandler.onPreCommand(CommandHandler.java:123)
[14:21:10 WARN]:        at sun.reflect.GeneratedMethodAccessor376.invoke(Unknown Source)
[14:21:10 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:21:10 WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[14:21:10 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[14:21:10 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:21:10 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[14:21:10 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[14:21:10 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
[14:21:10 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[14:21:10 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:21:10 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:21:10 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[14:21:10 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:21:10 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:21:10 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[14:21:10 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[14:21:10 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[14:21:10 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[14:21:10 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[14:21:10 WARN]:        at java.lang.Thread.run(Thread.java:745)
````

**Comment by wacossusca34** [comment]
sounds like it's not respecting your software freedoms... *runs*

Actually, looks like the console was allocated (new `ConsoleRenderer` instance), but it was never created (entities assigned, added to the world). This causes a few problems when trying to remove the consoles.

Technically, this shouldn't be possible unless you ran into another error while trying to create the console and it didn't finish, although there should be better error handling for this anyway.
